import JSZip from 'jszip';
import { SplitPart, Batch } from '@/types';
import { partToText } from './splitter';
import { estimateTokens } from './tokens';

function buildBatchReadme(
  batch: Batch,
  characterLimit: number,
  allowExceed: boolean,
  detectedType: string
): string {
  return `truncfix – Batch ${String(batch.index).padStart(2, '0')} of ${String(batch.totalBatches).padStart(2, '0')}
========================

This batch was generated by truncfix.com

Parts in this batch:     ${batch.parts.length}
Characters in this batch: ${batch.totalChars.toLocaleString()}
Estimated tokens:         ~${batch.estimatedTokens.toLocaleString()} (approx, chars÷4)
Character limit used:     ${characterLimit.toLocaleString()}
Allow exceed for large:   ${allowExceed ? 'Yes' : 'No'}
Source type:              ${detectedType}

--------------------------------------------------
HOW TO USE THIS BATCH
--------------------------------------------------

1. Upload the parts in this folder to a single AI conversation, in order.
2. After each upload, ask the model to confirm it received the complete part
   (request first 3 lines + last 5 lines + character count).
3. Once all parts in this batch are confirmed, work with that slice of context.

Parts in this batch:
${batch.parts
  .map(
    (p) =>
      `  - part-${String(p.index).padStart(2, '0')}  (${p.files.length} blocks, ${p.charCount.toLocaleString()} chars${p.exceedsLimit ? ' [EXCEEDED LIMIT]' : ''})`
  )
  .join('\n')}

Generated by truncfix on ${new Date().toISOString()}
`;
}

function buildMasterReadme(
  originalFileCount: number,
  totalChars: number,
  characterLimit: number,
  maxTokensPerZip: number,
  batches: Batch[],
  allowExceed: boolean,
  detectedType: string,
  filename: string
): string {
  const totalTokens = estimateTokens(totalChars);
  return `truncfix – Master Package
========================

This zip was generated by truncfix.com

Original filename:        ${filename}
Detected type:            ${detectedType}
Original blocks/files:    ${originalFileCount}
Total characters:         ${totalChars.toLocaleString()}
Estimated total tokens:   ~${totalTokens.toLocaleString()} (approx, chars÷4)
Character limit per part: ${characterLimit.toLocaleString()}
Max tokens per batch/zip: ${maxTokensPerZip.toLocaleString()}
Allow exceed for large:   ${allowExceed ? 'Yes' : 'No'}
Batches created:          ${batches.length}
Total parts created:      ${batches.reduce((s, b) => s + b.parts.length, 0)}

--------------------------------------------------
HOW TO USE
--------------------------------------------------

Each "batch-XX" folder is sized to stay under your max-tokens budget so you
can load one batch per conversation thread without overflowing context.

1. Start a new AI conversation for batch-01.
2. Upload its parts in order and confirm receipt.
3. Work with that slice of context.
4. When you need the next slice, open a new conversation and use batch-02, etc.

Batch summary:
${batches
  .map(
    (b) =>
      `  - batch-${String(b.index).padStart(2, '0')}/  → ${b.parts.length} parts, ${b.totalChars.toLocaleString()} chars, ~${b.estimatedTokens.toLocaleString()} tokens`
  )
  .join('\n')}

--------------------------------------------------
NOTES
--------------------------------------------------

- Blocks are kept whole whenever possible.
- A part only exceeds the character limit if you enabled the
  "Allow one part to exceed limit" toggle and a single block was larger.
- Token counts are approximate (characters ÷ 4).
- Generated by truncfix on ${new Date().toISOString()}
`;
}

/**
 * Creates a single zip that may contain multiple batch folders.
 * This is the preferred download shape when a max-tokens budget is set.
 */
export async function createBatchedZipBlob(
  batches: Batch[],
  characterLimit: number,
  maxTokensPerZip: number,
  originalFileCount: number,
  totalChars: number,
  allowExceed: boolean,
  detectedType: string,
  filename: string
): Promise<Blob> {
  const zip = new JSZip();
  const ext = detectedType === 'repomix' ? 'xml' : 'txt';

  for (const batch of batches) {
    const folderName =
      batches.length === 1
        ? '' // no subfolder if only one batch
        : `batch-${String(batch.index).padStart(2, '0')}/`;

    for (const part of batch.parts) {
      const text = partToText(part, characterLimit, detectedType, ext);
      const name = `${folderName}part-${String(part.index).padStart(2, '0')}.${ext}`;
      zip.file(name, text);
    }

    if (batches.length > 1) {
      const batchReadme = buildBatchReadme(
        batch,
        characterLimit,
        allowExceed,
        detectedType
      );
      zip.file(`${folderName}README.txt`, batchReadme);
    }
  }

  // Always include a master README at the root
  const master = buildMasterReadme(
    originalFileCount,
    totalChars,
    characterLimit,
    maxTokensPerZip,
    batches,
    allowExceed,
    detectedType,
    filename
  );
  zip.file('MASTER-README.txt', master);

  // Convenience: also put a README at root when there is only one batch
  if (batches.length === 1) {
    zip.file(
      'README.txt',
      buildBatchReadme(batches[0], characterLimit, allowExceed, detectedType)
    );
  }

  return zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
}

/** @deprecated kept for any old call sites during transition */
export async function createZipBlob(
  parts: SplitPart[],
  characterLimit: number,
  originalFileCount: number,
  totalChars: number,
  allowExceed: boolean
): Promise<Blob> {
  const batch: Batch = {
    index: 1,
    totalBatches: 1,
    parts,
    totalChars,
    estimatedTokens: estimateTokens(totalChars),
  };
  return createBatchedZipBlob(
    [batch],
    characterLimit,
    999999999,
    originalFileCount,
    totalChars,
    allowExceed,
    'repomix',
    'unknown'
  );
}
