import JSZip from 'jszip';
import { SplitPart } from '@/types';
import { partToXml } from './splitter';

/**
 * Builds the README content that ships inside every zip.
 */
export function buildReadme(
  originalFileCount: number,
  totalChars: number,
  characterLimit: number,
  parts: SplitPart[],
  allowExceed: boolean
): string {
  return `truncfix – Split Package
========================

This zip was generated by truncfix.com

Original file contained: ${originalFileCount} source files
Total characters:        ${totalChars.toLocaleString()}
Character limit used:    ${characterLimit.toLocaleString()}
Allow exceed for large:  ${allowExceed ? 'Yes' : 'No'}
Parts created:           ${parts.length}

--------------------------------------------------
HOW TO USE
--------------------------------------------------

1. Upload the parts to your AI chat **in order** (part-01, part-02, ...).
2. After each upload, ask the model to confirm it received the complete part
   (request first 3 lines + last 5 lines + character count).
3. Once all parts are confirmed, you can begin working with the full codebase.

Recommended upload order:
${parts.map(p => `  - part-${String(p.index).padStart(2, '0')}.xml  (${p.files.length} files, ${p.charCount.toLocaleString()} chars${p.exceedsLimit ? ' [EXCEEDED LIMIT]' : ''})`).join('\n')}

--------------------------------------------------
NOTES
--------------------------------------------------

- Each part contains complete source files whenever possible.
- A part will only exceed the character limit if you enabled the
  "Allow one part to exceed limit" toggle and a single source file
  was larger than the limit.
- Generated by truncfix on ${new Date().toISOString()}
`;
}

/**
 * Creates a zip blob containing all parts + README.
 */
export async function createZipBlob(
  parts: SplitPart[],
  characterLimit: number,
  originalFileCount: number,
  totalChars: number,
  allowExceed: boolean
): Promise<Blob> {
  const zip = new JSZip();

  // Add each part
  for (const part of parts) {
    const xml = partToXml(part, characterLimit);
    const name = `part-${String(part.index).padStart(2, '0')}.xml`;
    zip.file(name, xml);
  }

  // Add README
  const readme = buildReadme(originalFileCount, totalChars, characterLimit, parts, allowExceed);
  zip.file('README.txt', readme);

  // Generate blob
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  return blob;
}
